name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Frontend Docker Image
      run: |
        docker build -t my-frontend:latest ./frontend

    - name: Build Backend Docker Image
      run: |
        docker build -t my-backend:latest ./backend

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Frontend Docker Image
      run: |
        docker tag my-frontend:latest ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

    - name: Push Backend Docker Image
      run: |
        docker tag my-backend:latest ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy with Terraform
      run: |
        cd infra
        terraform init
        terraform apply -auto-approve
